django_movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('users/', include('users.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views

app_name = "movies"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create', views.CreateView.as_view(), name='create'),
    path('<int:pk>/edit', views.UpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.DeleteView.as_view(), name="delete"),
    path('secret', views.secretPage, name="secret")
]

users/urls.py
from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('<int:pk>/profile', views.ProfileUpdateView.as_view(), name='profile')
]

movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=300)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
      return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  hometown = models.CharField(max_length=100)

movies/forms.py
from django.forms import ModelForm
from .models import Movie

class MovieForm(ModelForm):
  class Meta:
    model = Movie
    fields = ["title"]

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required

from .models import Movie
from .forms import MovieForm

class IndexView(generic.ListView):
  model = Movie
  template_name = "movies/index.html"

class DetailView(generic.DetailView):
  model = Movie
  template_name = "movies/detail.html"

class CreateView(CreateView):
  model = Movie
  fields = ["title"]
  template_name = "movies/create.html"
  
  def get_success_url(self):
    return reverse('movies:detail', kwargs={'pk': self.object.pk})

class UpdateView(UpdateView):
  model = Movie
  fields = ["title"]
  template_name = "movies/edit.html"

  def get_success_url(self):
    return reverse('movies:detail', kwargs={'pk': self.object.pk})

class DeleteView(DeleteView):
  model = Movie
  success_url = reverse_lazy("movies:index")

@login_required
def secretPage(request):
  return HttpResponse('<h1>Secret page!</h1>')

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.models import User
from .models import Profile

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'registration/signup.html'

class ProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = Profile
    fields = ["hometown"]
    template_name = 'profile/detail.html'
    success_message = "Profile successfully updated!"

    def get_success_url(self):
        return reverse('users:profile', kwargs={'pk': self.object.pk})

movies/templates/movies/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>A Basic HTML5 Template</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <link href="{% static 'style.css' %}" rel="stylesheet">

</head>

<body>
  {% include 'movies/header.html' with user=user %}

  <div id="page_content" class="container">
    {% block page_content %}{% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/create.html
{% extends 'movies/base.html' %}

{% block page_content %}
  <form action="{% url 'movies:create' %}" method="post">
    {% csrf_token %}
      {{ form }}
      <input type="submit" value="Submit">
  </form>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block page_content %}
  <a class="pt-5" href="{% url 'movies:index' %}">All movies</a>

  <h2 class="mt-4">{{ movie.title }}</h2>
  <img src="{{movie.image.url}}" width="200px" />
  <div>
    <a class="btn btn-warning" href="{% url 'movies:edit' movie.id %}" >Edit</a>
    <form class="d-inline" action="{% url 'movies:delete' movie.id%}" method="post">
    {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Delete">
    </form>
  </div>
{% endblock %}

movies/templates/movies/edit.html
{% extends 'movies/base.html' %}

{% block page_content %}
  <form action="{% url 'movies:edit' movie.id%}" method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

movies/templates/movies/header.html
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Movies</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/movies">Movies </a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Options
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'users:profile' pk=user.id %}">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Signup</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block page_content %}
  <a class="btn btn-primary mt-5" href="{% url 'movies:create' %}">Add Movie</a>

  {% for movie in movie_list %}
    <div class="my-3">
      <a class="d-block" href="{% url 'movies:detail' movie.id %}"><h2>{{ movie.title }}</h2></a>
      <img src="{{movie.image.url}}" width="200px" />
    </div>
  {% endfor %}
{% endblock %}

movies/templates/movies/show.html
{{ movie.title }}
<a href="{% url 'movies:edit' movie.id %}" >Edit</a>
<form action="{% url 'movies:delete' movie.id%}" method="post">
{% csrf_token %}
  <input type="submit" value="Delete">
</form>
<a href="{% url 'movies:index' %}">All movies</a>

users/templates/profile/detail.html
{% extends 'movies/base.html' %}

{% block page_content %}
  {% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
  {% endif %}
  <form action="{% url 'users:profile' user.id%}" method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}